@startuml Console

class "ncurses library" << (h,Orange) >> {
    ncurses library functions
}

class Console {
    - {static} bool initialized
    --
    + {static} void init()
    + {static} void destroy()
    ..
    + {static} int getHeight()
    + {static} int getWidth()

    + {static} std::string getInputOfLength(int l)

    + {static} void moveCursor(int x, int y)

    + {static} void Print(int x, int y, const wchar_t* str)
    + {static} void Print(int x, int y, const char* str)

    + {static} void setColor(CONSOLECOLOR color = WHITE)

    + {static} void flush()
    + {static} void Clear()
    + {static} void Clear(int x, int y, int w, int h)
}

note top of Console
Interface between ncurses
and our program. No other part directly calls
any ncurses library function
end note

"ncurses library" .. Console
Console *-- CONSOLECOLOR

enum CONSOLECOLOR {
    BLACK
    RED
    GREEN
    YELLOW
    BLUE
    MAGENTA
    CYAN
    WHITE
}
@enduml
